apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-deploy
  labels:
    service: es-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: es-deploy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - es-deploy
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: init-sysctl
        image: busybox:1.30
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 20
          periodSeconds: 30
        ports:
        - containerPort: 9200
        - containerPort: 9300
