apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    service: mongo-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mongo-deploy
    spec:
      containers:
      - name: mongodb
        image: mongo:3
        ports:
        - containerPort: 27017
